### ISSUE TITLE
Add ability to autoclaim ORCID in Sandbox

### ISSUE THREAD

**Issue by jeremyf** [ORCID/ORCID-Source#1132]
It would be nice to auto-claim an ORCID when working with the Sandbox.
One possible option would be to allow a REQUEST header to auto-claim the Orcid that is being created.

```
X-AUTO-CLAIM=<password-to-apply-on-claim>
```

This would obviate the need for jumping over to Mailinator, finding the claim URI, and then jumping back to Orcid to claim the profile.

**Comment by rcpeters** [comment]
Closing this since create records via API is being sunsetted.

https://orcid.org/blog/2015/12/04/importance-opt
