### ISSUE TITLE
Orcid 

### ISSUE THREAD

**Issue by jeremyf** [ORCID/ORCID-Source#1507]
The rendered exception text is poor English. This appears to be bubbling up to the response status of creating an Orcid via the API.

Change

> User with this email already exist.

To

> User with this email already exists.

https://github.com/ORCID/ORCID-Source/blob/aeb70c2577b74d8a6fb723e532029d99d245b3b0/orcid-api-web/src/main/java/org/orcid/api/t2/server/delegator/impl/T2OrcidApiServiceDelegatorImpl.java#L257

**Comment by rcpeters** [comment]
Closing as we wont fix. On the plus side the V2 API has enumerations for errors messages so things like this will be easier to fix/adjust without breaking everyone. I believe enums for errors was also a suggestion received earlier.
