### ISSUE TITLE
BibTeX import problem

### ISSUE THREAD

**Issue by VladimirAlexiev** [ORCID/ORCID-Source#1732]
I'm trying to import http://vladimiralexiev.github.io/pubs/Alexiev-bibliography.bib and I get this error, which is not very informative:
"This file can not be read. Please check the BibTeX format and try again."

What's wrong with the file? I don't want to export out of google scholar since it doesn't have all my publications.

**Comment by VladimirAlexiev** [comment]
Thanks!!

**Comment by cagmanabdullah** [comment]
Dear Liz Krznari
 
Please could you check my bibtex file https://drive.google.com/open?id=0B-kx70nLigkkUjhIaTJYSzhTZVE
