### ISSUE TITLE
Clarify in the schema and documentation whether multiple work-citations are allowed. Add support for posting works with multiple citation formats

### ISSUE THREAD

**Issue by jstirnaman** [ORCID/ORCID-Source#1823]
Nothing in v1.2 suggests it doesn't allow multiple work-citations. The UI allows to change citation views, which suggests that multiple citation formats should be allowed when posting a work. The documentation only recommends preferring bibtex.

Still, I am unable to make the XML below validate. The validator is expecting work-type to immediately follow the first work-citation.
`
<orcid-work>
...
<short-description>...</short-description>
  <work-citation>
    <work-citation-type>formatted-apa</work-citation-type>
    <citation>Okuyemi, K. S., Harris, K. J., Scheibmeir, M., Choi, W. S., Powell, J., Ahluwalia, J. S., Okuyemi, K., Harris, K., Scheibmeir, M., Choi, W., Powell, J., &amp;amp; Ahluwalia, J. (2002). Light smokers: issues and recommendations.. Nicotine &amp;amp; tobacco research : official journal of the Society for Research on Nicotine and Tobacco. article, Oxford University Press.Okuyemi, Kolawole S., Harris, Kari Jo, Scheibmeir, Monica, Choi, Won S., Powell, Joshua (2002). Light smokers: issues and recommendations.. Nicotine &amp; tobacco research : official journal of the Society for Research on Nicotine and Tobacco, 4 Suppl 2, S103-12.</citation>
  </work-citation>
  <work-citation>
    <work-citation-type>bibtex</work-citation-type>
   <citation>@article{okuyemi_harris_scheibmeir_choi_powell_ahluwalia_okuyemi_harris_scheibmeir_choi_powell_ahluwalia_2002,  title={Light smokers: issues and recommendations.},  journal={Nicotine &amp;amp; tobacco research : official journal of the Society for Research on Nicotine and Tobacco},  publisher={Oxford University Press},  author={Okuyemi,  Kolawole S. and Harris,  Kari Jo and Scheibmeir,  Monica and Choi,  Won S. and Powell,  Joshua and Ahluwalia,  Jasjit S. and Okuyemi,  Ks and Harris,  Kj and Scheibmeir,  M. and Choi,  Ws and Powell,  J. and Ahluwalia,  Js},  year={2002},  month={Jan},  pages={S103-12}Okuyemi, Kolawole S., Harris, Kari Jo, Scheibmeir, Monica, Choi, Won S., Powell, Joshua (2002). Light smokers: issues and recommendations.. Nicotine &amp; tobacco research : official journal of the Society for Research on Nicotine and Tobacco, 4 Suppl 2, S103-12.</citation>
  </work-citation>
  <work-type>journal-article</work-type>
...
</orcid-work>
`

**Comment by rcpeters** [comment]
The XSD is part of the documentation. Only one citation is allowed per the XSD. @lizkrznarich could we make sure our other documentation reflects this?

**Comment by jstirnaman** [comment]
I realize that the XSD is part of the documentation. I didn't realize that maxOccurs always defaults to 1. Having the option to switch formats in the UI led me farther astray. Thanks - I think having it expressed elsewhere in the technical docs will be helpful.

**Comment by lizkrznarich** [comment]
@rcpeters @jstirnaman API documentation is updated at http://support.orcid.org/knowledgebase/articles/135422-xml-for-orcid-works , http://support.orcid.org/knowledgebase/articles/135758-anatomy-of-a-citation and http://members.orcid.org/api/xml-orcid-works
