### ISSUE TITLE
Feature Request: Initialized given-names

### ISSUE THREAD

**Issue by dshorthouse** [ORCID/ORCID-Source#1891]
A data source I am using to discover potential ORCID ids may/may not have initials as given-names. If your Lucene index had an EdgeNGram on given-names, to help accommodate incoming queries that contain abbreviated given-names, this would be immensely useful.

**Comment by dshorthouse** [comment]
Alternatively, an additional, computed field like "given-name-initials" with EdgeNGram would be equally useful and would not change the behaviour of your existing Solr field, "given-names". A relatively simple regex-based method from https://github.com/berkmancenter/namae/blob/master/lib/namae/name.rb#L178 might prove useful.

**Comment by wjrsimpson** [comment]
Hi David,

I think this is a good idea. A new field with EdgeNGram sounds like a good first step.

Please can you post the idea on the ORCID iDeas forum at http://support.orcid.org/forums/175591-orcid-ideas-forum, where it can be voted and commented on.

Best regards,

Will
