### ISSUE TITLE
switching among delegating profiles requires login of the delegate

### ISSUE THREAD

**Issue by helix84** [ORCID/ORCID-Source#1932]
In the current production version of ORCID (tested in Firefox and Chrome):

1) log in as a delegate of multiple accounts
2) switch to one of the delegated accounts

Expected behaviour (this was the case in the past):
Account is switched

Actual behaviour:
Login form is displayed, after entering the delegate account password, account is switched

**Comment by rcpeters** [comment]
@helix84 Are you still seeing this issue?

**Comment by helix84** [comment]
It's fixed now, thanks!
