### ISSUE TITLE
import from BibTeX - save button doesn't work

### ISSUE THREAD

**Issue by helix84** [ORCID/ORCID-Source#1933]
In the current production version of ORCID (tested in Firefox and Chrome):

(This was done for a delegated account)

1) Import from BibTeX (using Web of Science BibTeX export, both multiple records per file and single record per file)
2) Records show in a list to import with a Save button and a Delete button
3) Click the Save button next to any of the records

Expected behaviour:
Record is added to Works

Actual behaviour:
Nothing happens

Note: When one of the records was missing an external ID, so there was an Edit button instead of the Save button, which displayed an edit form. After filling in the external ID, this record was added to Works successfully.

**Comment by rcpeters** [comment]
Fix already in next release. You can test in qa.orcid.org if you want to verify.
https://trello.com/c/Ed38bVHK/1938-bibtex-save-doesn-t-work-for-items-with-type-inproceedings-and-a-doi-listed
https://github.com/ORCID/ORCID-Source/pull/1924
