### ISSUE TITLE
When IDing "same identifiers" ORCID should recognize both link and stand alone

### ISSUE THREAD

**Issue by ethanwhite** [ORCID/ORCID-Source#1996]
I'm not sure if this is the right place to report this, but I noticed the following issue with the "same identifiers" functionality.

Since there are two common forms for DOIs, the DOI itself and the DOI preceded by http://dx.doi.org/ the site should recognize that 

`http://dx.doi.org/10.1371/journal.pone.0014651`

and 

`10.1371/journal.pone.0014651`

refer to the same object. This does not currently occur: 

![screenshot from 2015-05-28 14 02 05](https://cloud.githubusercontent.com/assets/744427/7869923/f01e2e58-0542-11e5-99dc-b89e27cc3104.png)

**Comment by caoyler** [comment]
Hi,

For questions about how the ORCID Registry works, please contact ORCID Support at support@orcid.org. Our support team will be more than happy to follow up with you about this, but we aren't active on GitHub.

Thanks,
-Catalina
ORCID Support
