### ISSUE TITLE
Release notes are outdated

### ISSUE THREAD

**Issue by gneissone** [ORCID/ORCID-Source#1999]
Please update or delete [RELEASE.MD] (https://github.com/ORCID/ORCID-Source/blob/master/RELEASE.md). It is linked on some old blog posts and idea board responses from the ORCID team. It gives the (fortunately incorrect) impression that work has stalled.

**Comment by lpaglione** [comment]
Hi -- thanks for your note. The release notes have been updated. Best, Laura
