### ISSUE TITLE
http://pub.sandbox.orcid.org/ returning 405 error code

### ISSUE THREAD

**Issue by samc1213** [ORCID/ORCID-Source#2066]
'Accept: application/json' --data 'client_id=APP-WT2PY6SQPAPXUKP4&client_secret=******************&grant_type=authorization_code&redirect_uri=http://127.0.0.1:8888&code=oqJqus' http://pub.sandbox.orcid.org/
HTTP/1.1 405 Method Not Allowed
Server: nginx/1.1.19
Date: Tue, 07 Jul 2015 22:49:24 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *

{"message-version":"1.2","orcid-profile":null,"orcid-search-results":null,"error-desc":{"value":"It is possible that this is a bug. If you could raise an issue in Github it would be much appreciated. Thanks, the ORCID team"}}

**Comment by caoyler** [comment]
Hi Sam,

Can you raise this issue with our support team at support@orcid.org? We'll be able to offer more help there. But I can add, if you're trying to exchange an authorization code for an access token you should be on the member API. The public API doesn't support three legged authentication.

Thanks,
-Catalina
ORCID Support
