### ISSUE TITLE
Feature Request: Directly downloadable bibtex file from Web UI

### ISSUE THREAD

**Issue by vdmitriyev** [ORCID/ORCID-Source#2275]
I'm not quite sure if you have this feature already in non released version, but it would be very nice to have an ability to directly download bibtex of particular publication (work) from web ui (the same which was uploaded by creator of work). For a moment this functionality available via ORCID API, but  integrating it into web ui can enhance user experience.

**Comment by TomDemeranville** [comment]
This is now live and complete.
