### ISSUE TITLE
ACTIVITIES_UPDATE

### ISSUE THREAD

**Issue by dbolser-ebi** [ORCID/ORCID-Source#2432]
https://github.com/ORCID/ORCID-Source/blob/master/orcid-core/src/main/resources/i18n/messages_en.properties#L1203

What does this mean?

**Comment by rcpeters** [comment]
See '/activities/update' on page https://members.orcid.org/api/orcid-scopes

**Comment by dbolser-ebi** [comment]
Many thanks, Actually was confused by this one:

org.orcid.jaxb.model.message.ScopePathType.ACTIVITIES_UPDATE=Create or update your activities
org.orcid.jaxb.model.message.ScopePathType.ACTIVITIES_UPDATE.longDesc=Will allow this organization or application to add or update activities in your ORCID record

The description you linked to was much more informative, "Update Research Activities". However, I'm still a bit confused by the use of the term 'activities' here.

**Comment by rcpeters** [comment]
Hi Dan, for reference you can send emails to support@orcid.org. Activities
are one of the following education, employment, funding, work or
peer-review. If you log into ORCID you will see a section for each of those.

- Rob

On Mon, Nov 23, 2015 at 7:53 AM, Dan Bolser <notifications@github.com>
wrote:

> Many thanks, Actually was confused by this one:
>
> org.orcid.jaxb.model.message.ScopePathType.ACTIVITIES_UPDATE=Create or
> update your activities
> org.orcid.jaxb.model.message.ScopePathType.ACTIVITIES_UPDATE.longDesc=Will
> allow this organization or application to add or update activities in your
> ORCID record
>
> The description you linked to was much more informative, "Update Research
> Activities". However, I'm still a bit confused by the use of the term
> 'activities' here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ORCID/ORCID-Source/issues/2432#issuecomment-158976202>
> .
>



-- 
Robert Peters
info@rcpeters.com
805.440.9056
