### ISSUE TITLE
Deleting URL for source fails

### ISSUE THREAD

**Issue by tzeumer** [ORCID/ORCID-Source#2960]
Currently it is not possible to empty an URL field (e.g. after merging records and using ones own copy). Emptying the URL field and saving is ignored. Just using a space leads to an "please correct error" message.

**Comment by rcpeters** [comment]
Click the trashcan?

**Comment by tzeumer** [comment]
I'm not talking about the websites on the left. Am I too stupid?

![orcid_url](https://cloud.githubusercontent.com/assets/119825/16461329/4fab43f6-3e2c-11e6-8548-9998d9ef4b39.jpg)

**Comment by rcpeters** [comment]
You're not providing enough detail. I tested researcher websites (different section on the left side). Now I've tested adding works and I have no issue deleting the text and saving a work.

**Comment by tzeumer** [comment]
Sorry. I hope this explains it sufficiently
1. Open "Work" (record)
2. Empty URL field & save
3. After page reload, the url is still there (or back again

![step1](https://cloud.githubusercontent.com/assets/119825/16462280/d1d16f78-3e30-11e6-9bc0-984708c013ff.jpg)

![step2](https://cloud.githubusercontent.com/assets/119825/16462287/d7c1ff2e-3e30-11e6-9bc5-4d03fae10df7.jpg)

![step3](https://cloud.githubusercontent.com/assets/119825/16462293/db46060e-3e30-11e6-87a1-dae15d18ed3d.jpg)

**Comment by rcpeters** [comment]
Thanks @tzeumer, you should see a fix in the next week or two. We don't track those issues on github. @caoyler file a ticket on trello under qa errors assign to @amontenegro.

**Comment by amontenegro** [comment]
Got it, I will be working on it.

**Comment by amontenegro** [comment]
This PR will fix this issue: https://github.com/ORCID/ORCID-Source/pull/2964
