### ISSUE TITLE
Bibtex import creates duplicates

### ISSUE THREAD

**Issue by VladimirAlexiev** [ORCID/ORCID-Source#3001]
I imported http://vladimiralexiev.github.io/pubs/Alexiev-bibliography.bib to https://orcid.org/my-orcid and now it says I got 102 works. 
However, the total number of entries in this file is 70:

type|count
---|---
Book (author), thesis, conference proceedings (editor)   |3
Tech reports, manuals, deliverables, ontologies  |25
Conference papers, journal articles      |19
Presentations, posters, blog posts       |22
TOTAL    |70

It would be nice if the importer looked for existing entries (eg by same title and authors) and merged them.

**Comment by rcpeters** [comment]
Hi Vladimir,
Ideas go here:
http://support.orcid.org/forums/175591-general

**Comment by VladimirAlexiev** [comment]
http://support.orcid.org/forums/175591-orcid-ideas-forum/suggestions/3342355-create-a-function-to-remove-duplicates-in-works: it ways "Done" but the comments there really show it is not.
How can we stimulate more work on merging duplicate Works?
