### ISSUE TITLE
Pressing enter on oauth signin fails

### ISSUE THREAD

**Issue by oskanberg** [ORCID/ORCID-Source#3109]
On the `/oauth/signin` form, pressing the enter key will not authorise correctly.

Instead, a network call to:
`https://sandbox.orcid.org/oauth/custom/authorize.json` fails with a `500 Internal Server Error`.

Clicking 'authorize' works correctly.

Verified on Mac Chrome, Windows Chrome, Windows Firefox.

**Comment by rcpeters** [comment]
Tested and we must of fixed this with another ticket.

**Comment by oskanberg** [comment]
Unfortunately this is not fixed. Steps to reproduce:

1. Visit OAUTH login page (for example use the [ORCID QRCode generator](http://qrcode.orcid.org/) and go to login)
2. Enter your login details and press the enter key

This is the result in the console:
<img width="975" alt="screen shot 2017-02-06 at 09 21 20" src="https://cloud.githubusercontent.com/assets/1401665/22641289/fe77bb38-ec4d-11e6-93b8-836b311ad443.png">

I have tested this on latest Firefox, Chrome, and Safari on macOS Sierra.
