### ISSUE TITLE
Swagger.json FORMATTED_UNSPECIFIED error

### ISSUE THREAD

**Issue by rcaap-fccn** [ORCID/ORCID-Source#3244]
The generated https://pub.orcid.org/resources/swagger.json file has an error. It defines an enumeration with FORMATTED_UNSPECIFIED and sets the default value to an existing value: "formatted-unspecified"
`
"Citation" : {
      "type" : "object",
      "required" : [ "citation-type", "citation-value" ],
      "properties" : {
        "citation-type" : {
          "type" : "string",
          "xml" : {
            "namespace" : "http://www.orcid.org/ns/work"
          },
          "enum" : [ "**FORMATTED_UNSPECIFIED**", "BIBTEX", "FORMATTED_APA", "FORMATTED_HARVARD", "FORMATTED_IEEE", "FORMATTED_MLA", "FORMATTED_VANCOUVER", "FORMATTED_CHICAGO", "RIS" ],
          **"default" : "formatted-unspecified"**
        },
        "citation-value" : {
          "type" : "string",
          "xml" : {
            "namespace" : "http://www.orcid.org/ns/work"
          }
        }
      }
    },
`

**Comment by rcaap-fccn** [comment]
Sorry, I meant the unexisting value "formatted-unspecified"

**Comment by TomDemeranville** [comment]
Strangely, Citation is the only enumeration with a default value.  I have removed this and the change should be in production within a couple of weeks.  It does mean you MUST now supply a CitationType.

**Comment by TomDemeranville** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Remove default citation style](https://trello.com/c/er7uS7nn/3334-remove-default-citation-style)
