### ISSUE TITLE
Disambiguated institutions: conflicting Ringgold ids

### ISSUE THREAD

**Issue by wetneb** [ORCID/ORCID-Source#3297]
There seems to be an issue with the disambiguation of institutions. Here is an example:
* [0000-0002-9837-3803](http://orcid.org/0000-0002-9837-3803) has "Université de Montpellier, FR" as institution, bearing the Ringgold id 138213 ([see in the API](http://pub.orcid.org/v1.2/0000-0002-9837-3803/orcid-profile))
* [0000-0003-1480-1039](http://orcid.org/0000-0003-1480-1039) has "Pushkin State Russian Language Institute, RU" as institution, bearing the *same* Ringgold id 138213 ([see in the API](http://pub.orcid.org/v1.2/0000-0003-1480-1039/orcid-profile))

As far as I can tell these two institutions are very different and there are no plans to merge them! So, the value of this disambiguation is rather doubtful.

**Comment by alainna** [comment]
Looking at the record http://orcid.org/0000-0003-1480-1039, the record holder selected Communauté d'Universités et Etablissements Languedoc-Roussillon Universités (ringgold 138213) from the pick-list and then input manually "Pushkin State Russian Language Institute".

**Comment by wetneb** [comment]
I tried to reproduce this in the sandbox. I first selected "Université de Montpellier" and added it to the record: I get Ringgold id 138213.
Then, I did what you describe: add an institution by first picking "Université de Montpellier" from the autocompletion list, and then editing all the fields (name, city and country).
I have added two dummy institutions (that are not likely at all to have a Ringgold id) and both were assigned ringgold id 27037 (which is different from the original one).
This seems to be a bug, although slightly different from the one I was originally reporting as these fake Ringgold ids are different from the autocompleted one.

Here is the record I created: http://sandbox.orcid.org/0000-0002-2558-1820

**Comment by wjrsimpson** [comment]
Hi Antonin,

Thanks for looking into disambiguated organizations!

The behavior with your fake organizations is what we want. We allow users to select an organization from the drop down list, and then modify the info. This allows users to show the organization exactly how they like on their ORCID record, but we still link to the disambiguated organization for reporting.

If another user enters the same organization info, we link it to the same disambiguated org selected by the first user.

Users can make mistakes so sometimes we have bad data, that is true. However, most of the time it works well, and the users make useful changes. For example, showing the name of the organization in a different language.

However, I can see another problem with "Université de Montpellier" pointing to Ringgold ID 138213. I believe Ringgold caused that problem. Originally, 138213 was "Université de Montpellier". But at some point Ringgold changed it to "Communaute d'Universites et Etablissements Languedoc-Roussillon Universites". They should not have done that, it's a completely different organization! I don't know exactly when it happened, but I think some time at the end of 2014 or beginning of 2015.

We are going to look into cleaning up the bad changes from Ringgold.

Antonin, please can you send an further queries to support@orcid.org?

Cheers,

Will

**Comment by wetneb** [comment]
Thanks for these explanations and good luck with the cleanup!
I guess I will simply drop your identifiers and do my own deduplication, I suppose…

I will use suport@orcid.org next time.

**Comment by wetneb** [comment]
For reference, here is a more substantial example, extracted from the ORCID 2016 data dump. These are all the names associated with the ringgold ID 14724, and the number of occurrences of the (id,name) pair.

```
11      University of Maryland University College
4       University of Catania
3       University of Edinburgh
3       University of Cordoba
2       University of Poitiers
2       University of Zielona Góra
2       University of Ouagadougou
1       University of Bartın
1       University of Genoa
1       University of extremadura
1       University of Zaragoza
1       University of Pavia
1       University of Stockholm
1       UIT The Arctic University of Tromsø
1       University of Reims
1       University of Paris-Saint-Denis
1       University of Macedonia
```

More than half of them are clearly different from the institution represented by the ringgold id (the first one).

I imagine this institution was selected because "university" occurs twice in the name, so users typed something like "univ", autocompleted to "University of Maryland University College", and then fixed the name after "University of ".

**Comment by pigsonthewing** [comment]
There is some [further discussion of this issue on Wikidata](https://www.wikidata.org/wiki/Wikidata:Property_proposal/Ringgold_identifier).

(Wikidata now has a property, [P3500](https://www.wikidata.org/wiki/Property:P3500), for Ringgold IDs.
