### ISSUE TITLE
Support for Linked Data Notifications

### ISSUE THREAD

**Issue by csarven** [ORCID/ORCID-Source#3416]
What's the current 'inbox' implementation based on?

I would like to suggest implementing https://www.w3.org/TR/ldn/ :

* One trivial way to support LDN would be where the profile URI (i.e., the *target* in LDN terms) have the `ldp:inbox` relation with the value of the Inbox URL. The Inbox URL can be on orcid.org or at a different domain. If for instance I want people to send me notifications through discovering my ORCID URL, I should be able to add this value simply through the profile editor UI (under Websites?) with perhaps the 'Description' value being 'Inbox' and the 'URL' being an Inbox URL (that can receive and serve notifications from). Access controls are naturally set at the Inbox URL.

* If the current ORCID inbox can be reused here, great. Perhaps by default every profile can have the `ldp:inbox` relation pointing at `https://orcid.org/0000-0002-0880-9125/inbox/` or something. This would mean that ORCID Inboxes can work as *receivers* (in LDN terms). Being able to store and serve notifications essentially, and let them be discoverable as well.

*Remark*: having a conforming LDN receiver implementation does not require it to be LDP or anything like that. Existing LDP implementations just happen to be conforming LDN receivers out of the box. The property `ldp:inbox` is in the LDP namespace, and is used only by a resource (the profile URI in our case).

Happy to discuss further or help out where necessary.

**Comment by stain** [comment]
I assume you mean the content-negotatiated RDF output from ORCID, e.g. from

    curl -L -H "Accept: text/turtle" http://orcid.org/0000-0001-9842-9718

which lists the "Websites" URLs depending on their description:

```turtle
<http://orcid.org/0000-0001-9842-9718>
        a                  foaf:Person , prov:Person ;
        rdfs:label         "Stian Soiland-Reyes" ;
        rdfs:seeAlso       <http://soiland-reyes.com/stian/#me> ;
        prov:alternateOf   <http://soiland-reyes.com/stian/#me> ;
        foaf:homepage      <http://soiland-reyes.com/stian/work/> ;
        foaf:page          <http://www.manchester.ac.uk/research/soiland-reyes/publications> , <https://twitter.com/soilandreyes> , <http://scholar.google.com/citations?user=OeBjonkAAAAJ> , <http://academic.research.microsoft.com/Author/5200832> , <http://uk.linkedin.com/in/stain/> , <https://github.com/stain> , <http://www.slideshare.net/soilandreyes/> .
```

(Perhaps the description should also be shown in literal somehow.. as an `oa:Annotaton`?)

The magic for choosing alternate properties than `foaf:page` is here
in [RDFMessageBodyWriter.describeResearcherUrls()](https://github.com/ORCID/ORCID-Source/blob/master/orcid-api-common/src/main/java/org/orcid/api/common/writer/rdf/RDFMessageBodyWriter.java#L378)

I'm afraid these  properties are not described anywhere else.. but adding handling of new "magic" URL description here like "LDP Inbox" and "PIM" would achieve what you want.

However using that (if we document it properly) would also mean showing the LDP Inbox and PIM Space at the normal browser HTML representation, but the LDP/PIM might not have a reasonable HTML representation themselves. So perhaps non-human "Websites" should be hidden from its listing of Websites? (This would include the `FOAF` I guess)

**Comment by csarven** [comment]
This is a two step process: The simplest thing to start off would be to allow profile owners to add the "Inbox" relation. That way people can use an Inbox of their choice. If ORCID wants to introduce/host Inboxes for profiles, that feature can be implemented separately.

**Comment by csarven** [comment]
I think the inbox (and storage) URLs should be human-visible by default. We can't foresee how inbox representations will be - well, at least available in JSON-LD. We let profile owners and inbox owners decide for themselves, i.e., profile owners choose to link to their Inbox which may or may not have a human-friendly view.

**Comment by stain** [comment]
Thanks! See it in use: https://twitter.com/csarven/status/905422007436795904
