### ISSUE TITLE
Use client's Origin value for Access-Control-Allow-Origin value to handle withCredentials requests

### ISSUE THREAD

**Issue by csarven** [ORCID/ORCID-Source#3419]
>A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'https://dokie.li' is therefore not allowed access. The credentials mode of an XMLHttpRequest is controlled by the withCredentials attribute.

In other words, if the client makes a request to the profile URL with `withCredentials` set in the XHR request, the current `Access-Control-Allow-Origin: *` prevents the request from loading. The way to handle is to take client's `Origin` header value from their request, and use that as the value for `Access-Control-Allow-Origin` instead of `*`.

**Comment by rcpeters** [comment]
That URL, you are assuming this isn't intentional.

**Comment by csarven** [comment]
Is the intention to lock ORCID profile URIs (or other resources) to be only used within the ORCID system and/or its partners? Is the possibility to reuse profile URIs in other open Web systems a not desired goal or rather forbidden? What is intended exactly?

The whole point of this issue is to allow client applications to reuse existing ORCID profiles. Some clients default to having withCredentials set to true so that session tokens for instance can persist over different requests at a (sub)domain.

**Comment by rcpeters** [comment]
Can I get some concert examples in curl form? Many URI are meant for external use, however that doesn't mean we want credentials to be used in a users browser (where they are easily stolen) vs credentials used server side (or via a secure proxy for clients credentials).
