### ISSUE TITLE
Journal Title in /works

### ISSUE THREAD

**Issue by mikecrabb** [ORCID/ORCID-Source#3608]
APIv1 allowed for you to get the name of journal/conference that a publication was presented at. Doesn't seem to be similar functionality in the /works part of APIv2.0

**Comment by TomDemeranville** [comment]
Do you mean the contents of the "Journal title" field in the UI?

It's on line 59 of the schema: https://github.com/ORCID/ORCID-Source/blob/master/orcid-model/src/main/resources/record_2.0/work-2.0.xsd

`<xs:element name="journal-title" type="work:journal-title" minOccurs="0" maxOccurs="1" />`

**Comment by mikecrabb** [comment]
Yes, that's what I'm looking for, but that isn't appearing in the live version of the API (at least not on my ID and 4 others I've tried)

**Comment by rcpeters** [comment]
@mikecrabb please see https://members.orcid.org/api/tutorial/read-orcid-records you have to call /work/[put code] to get the full details of a work.

**Comment by mikecrabb** [comment]
@rcpeters Cheers! Got it now.
