### ISSUE TITLE
Reopen of #3608 - journal-title in /works

### ISSUE THREAD

**Issue by mikecrabb** [ORCID/ORCID-Source#3617]
Reopening of issue #3608. Despite this being on line 59 of the schema

https://github.com/ORCID/ORCID-Source/blob/master/orcid-model/src/main/resources/record_2.0/work-2.0.xsd

`<xs:element name="journal-title" type="work:journal-title" minOccurs="0" maxOccurs="1" />
`

journal-title does not appear when requested from the API

**Comment by rcpeters** [comment]
@mikecrabb please see https://members.orcid.org/api/tutorial/read-orcid-records you have to call /work/[put code] to get the full details of a work.

**Comment by mikecrabb** [comment]
Cheers! Got it now
