### ISSUE TITLE
BibTeX import fails to recognize WoS ID, preventing deduplication

### ISSUE THREAD

**Issue by helix84** [ORCID/ORCID-Source#3673]
In case where a DOI is not available, deduplication in the ORCID interface can still occur automatically using other external IDs like the Web of Science ID (also called UT, ISI or WOSUID).

BibTeX records exported from Web of Science do include the ISI indentifier (twice), as can be seen in the example record below. (The "ISI:" prefix should be dropped, the canonical form of the identifier is just "A1997XZ23900045".)

The problem is that the ORCID BibTeX import fails to extract the identifier into ORCID "WOSUID" external identifier field.

````
@article{ ISI:A1997XZ23900045,
Author = {Kafka, S and Kosmrlj, J and Klasek, A},
Title = {{Changes of 3-hydroxyquinoline-2,4-(1H,3H)-diones in alkaline medium}},
Journal = {{CHEMICKE LISTY}},
Year = {{1997}},
Volume = {{91}},
Number = {{9}},
Pages = {{674-675}},
Note = {{50th Anniversary Meeting of the Chemical-Society, ZLIN, CZECH REPUBLIC,
   SEP 08-11, 1996}},
Organization = {{Chem Soc}},
Abstract = {{The title compounds (I) in benzene solution are changed by the action of
   aqueous or ethanolic solution of potassium hydroxide at room temperature
   to the mixtures of compounds II-V. The ratios of products depend on the
   substitution of educts I and on the reaction conditions. By the action
   of solid potassium hydroxide on the compounds I or II, the compounds III
   are formed.}},
Publisher = {{CHEMICKE LISTY}},
Address = {{PELLEOVA 24, PRAGUE 6, CZECH REPUBLIC 160 00}},
Type = {{Article; Proceedings Paper}},
Language = {{English}},
Affiliation = {{Kafka, S (Reprint Author), TECH UNIV BRNO,FAC TECHNOL ZLIN,NAM TG MASARYKA 275,ZLIN 76272,CZECH REPUBLIC.
   UNIV LJUBLJANA,FAC CHEM \& CHEM TECHNOL,LJUBLJANA 1000,SLOVENIA.}},
ISSN = {{0009-2770}},
Research-Areas = {{Chemistry}},
Web-of-Science-Categories  = {{Chemistry, Multidisciplinary}},
ResearcherID-Numbers = {{Kafka, Stanislav/H-6389-2012
   Klasek, Antonin/H-6363-2012}},
ORCID-Numbers = {{Kafka, Stanislav/0000-0001-6392-8007
   }},
Number-of-Cited-References = {{3}},
Times-Cited = {{0}},
Usage-Count-(Last-180-days) = {{0}},
Usage-Count-Since-2013 = {{1}},
Journal-ISO = {{Chem. Listy}},
Doc-Delivery-Number = {{XZ239}},
Unique-ID = {{ISI:A1997XZ23900045}},
}
````

**Comment by helix84** [comment]
Correction: Records imported from WoS to ResearcherID and from ResearcherID to ORCID have WOSUID in the following format: WOS:A1997XZ23900045

IMHO the import process from ResearcherID to ORCID should be changed to convert WOSUID to the canonical form, but if you decide against that, then BibTeX imports would need to change ISI:A1997XZ23900045 to WOS:A1997XZ23900045.

**Comment by rcpeters** [comment]
ResearcherId is an ORCID member and they push the ID to our system in the form they choose. WOS vs ISI should be brought up with them. 

Currently we'll import bibTex entries of doi, pmid, eprint, and isbn. If there was a wos entry would would consider importing it. However Unique-ID could be ANY:THING. Which would make our job incredibly hard if we start thinking about all the different IDs and forms of IDs out there.

We do have a project to normalize IDs passed to us. But it will be a while before we complete it. Additionally we would still expect type to be correctly passed instead of us guessing what it is based of the value of the ID.

We also have a ongoing project to allow grouping in the interface. However neither of those directly address the issue raised. 

What is the source of the bibtex and can we get them to add wos?

**Comment by helix84** [comment]
> ResearcherId is an ORCID member and they push the ID to our system in the form they choose. WOS vs ISI should be brought up with them.

I'll postpone this until we reach a conclusion here. It only makes sense to change once there is more than one source pushing the data.

As a curious aside, some records which went WoS->ResearcherID->ORCID do have the WOISUID field and some do not. I haven't figured out the pattern yet.

> What is the source of the bibtex and can we get them to add wos?

I exported the BibTeX record directly from the WoS web interface.

> If there was a wos entry would would consider importing it. However Unique-ID could be ANY:THING.

Well, that's what it is. ISI is an old name for WoS. I understand that you'd prefer if it were qualified in the attribute name, not value. I can understand that. On the other hand, WoS is a much bigger fish than ORCID, so I expect much more inertia there. They have integrations with many other systems (e.g. reference managers) which would need to change, too.

**Comment by helix84** [comment]
> We do have a project to normalize IDs passed to us.

> We also have a ongoing project to allow grouping in the interface.

I'd like to learn more/participate. Where can I read up on them?

**Comment by rcpeters** [comment]
@TomDemeranville do we have enough of a architecture document to share for the normalization project. Regardless we should get a meeting going to gain extra insights.

@helix84 The other project is mostly front end Angular.js work is that something you are interested in?

**Comment by TomDemeranville** [comment]
It's worth noting that IDs we do support via Bibtex import ( doi, pmid, eprint, and isbn) are valid Bibtex according to the Citeproc citation sytle library (CSL) parser, the others being proposed on this thread are not.  This is the parser used by many desktop reference managers, including Zotero.

**Comment by rcpeters** [comment]
Closed until WOSUID is part of Citeproc (https://github.com/Juris-M/citeproc-js-docs/blob/master/index.rst).
