### ISSUE TITLE
orcid-uri does not support HTTPS

### ISSUE THREAD

**Issue by mfenner** [ORCID/ORCID-Source#3819]
The `orcid-uri` property only supports http, whereas the ORCID display guidelines recommend https.

See https://github.com/ORCID/ORCID-Source/blob/master/orcid-model/src/main/resources/common_2.0/common-2.0.xsd#L753-L762

**Comment by stain** [comment]
I disagree,

It *is* confusing in the [guidance](https://support.orcid.org/knowledgebase/articles/116780-structure-of-the-orcid-identifier) as it can seem to recommend **three** styles of ORCIDs:

> Below are some example ORCID iDs with checksums as described above and expressed in the proper format. 
> * `orcid.org/0000-0002-1825-0097`
> * `https://orcid.org/0000-0001-5109-3700`
> * `http://orcid.org/0000-0002-1694-233X`

but above we read more formally:

> **Expressing the ORCID iD**
> The ORCID iD is expressed as a HTTP URI; the number is proceeded by "http://orcid.org/". A hyphen is inserted every 4 digits to aid readability. 
> 
> 
> **Storage of the ORCID iD in a database**
> When stored, the ORCID iD should be expressed as a URI: http://orcid.org/xxxx-xxxx-xxxx-xxxx, (with the protocol (http://), and with hyphens in the number xxxx-xxxx-xxxx-xxxx). 


Surely "database" here should also include schemas and XML documents used in APIs and Linked Data, including ORCIDs own XSD.

**Comment by rcpeters** [comment]
Over the next month we are moving the https as the official form:
https://orcid.org/blog/2017/11/02/canonical-form-orcid-id-coming?ref=email
