### ISSUE TITLE
Swagger API docs incorrect or incomplete for POST /works

### ISSUE THREAD

**Issue by kardeiz** [ORCID/ORCID-Source#3903]
The Swagger API docs at https://api.sandbox.orcid.org/v2.0/#/ state that the response success code for POST /works (`createWorks`) should be 201. However, it looks like it is actually [returning 200 on success](
https://github.com/ORCID/ORCID-Source/blob/master/orcid-api-web/src/main/java/org/orcid/api/memberV2/server/delegator/impl/MemberV2ApiServiceDelegatorImpl.java#L357). 

I have an app that was doing a bulk works create (on the Sandbox) that was unexpectedly failing on `worksCreate` because I was checking that the response code was 201.

**Comment by TomDemeranville** [comment]
Should bulk post return a 201, or should swagger be updated to say it
returns a 200?

I say the former makes the most sense as it would match individual post.

**Comment by TomDemeranville** [comment]
https://github.com/ORCID/ORCID-Source/pull/3971
