### ISSUE TITLE
Bibtex import error

### ISSUE THREAD

**Issue by cagmanabdullah** [ORCID/ORCID-Source#3962]
Hi,

When I try to import my bibtex file (https://drive.google.com/open?id=0B-kx70nLigkkUjhIaTJYSzhTZVE) I see the message "This file cannot be read. Please check the BibTeX formatting and try again."

What is the wrong? Please help me about this trouble.

**Comment by alainna** [comment]
@cagmanabdullah 
Please contact support@orcid.org with your BibTeX file so they can investigate. Please also provide further information about how you generated the file -- there are some systems which may require additional filters, or that you export a certain version of the BibTeX file.

**Comment by cagmanabdullah** [comment]
Thanks alainna
