### ISSUE TITLE
support more kinds of URLs in bibtex records

### ISSUE THREAD

**Issue by VladimirAlexiev** [ORCID/ORCID-Source#3963]
I make my bibliography http://vladimiralexiev.github.io/pubs/ with bibbase.org.
Bibbase supports any sort of URL in fields named url_WHATEVER.
In particular it's very useful to cite both a paper and the attendant presentation (slides) in the same record.
I use the following kinds (from my emacs configuration):
```elisp
   ("url" "URL if the document is available online.")
   ("url_Slides" "URL to a presentation")
   ("url_PPT" "URL to PPT version")
   ("url_HTML" "URL to continuous HTML version")
   ("url_PDF" "URL to PDF version")
   ("url_Video" "URL of a video")
   ("url_arXiv" "URL of the document on arXiv")
   ("url_CiteSeer" "URL of the document on CiteSeer")
   ("url_LOV" "URL of Linked Open Vocabularies record")
   ("url_TR" "URL of a TechnicalReport on institution site")
   ("url_Blog" "URL of a Blog")
   ("url_Source" "URL of Source code")
   ("url_Published" "URL of the document in an official publication, eg journal")
   ("url_Preprint" "URL of a Preprint")
   ("url_Appendix" "URL of an Appendix")
   ("url_Other" "URL to Other version of a document (eg 2-up)")
```
Would it be possible for ORCID to import more kinds of URLs, or maybe all of them, consuming the same pattern url_WHATEVER?

**Comment by rcpeters** [comment]
ORCID records only support one URL per a work (although many identifiers per including URLs are allowed).
