### ISSUE TITLE
deduplicate by URL

### ISSUE THREAD

**Issue by VladimirAlexiev** [ORCID/ORCID-Source#3964]
If you import the following record twice, it results in duplicates.
```bibtex
@TechReport{HCLS-profile,
  title        = {{Dataset Descriptions: HCLS Community Profile}},
  author       = {Alasdair J. G. Gray and Joachim Baran and M. Scott Marshall and Michel Dumontier and Vladimir Alexiev and others},
  month        = may,
  year         = 2015,
  url          = {http://www.w3.org/TR/hcls-dataset/},
  keywords     = {Data profiling, Dataset descriptions, Metadata, Provenance, FAIR data, HCLS, dataset, VOID, ontology, Bioinformatics, Taxonomy, Computational Science},
  institution  = {Semantic Web in Health Care and Life Sciences Interest Group (HCLSIG)},
}
```
#3673 discusses different kinds of identifiers used for deduplication.
Could you also deduplicate by URL? I think that if two records have the same URL, it is fair to assume they describe the same work.

(Note: #3963 asks for more kinds of URLs to be handled, but I think only pure `url` should be used for deduplication)

**Comment by rcpeters** [comment]
Sorry we only group by external identifiers.
