### ISSUE TITLE
ORCID OAuth authorize page shows ‘null’ string if surname is empty

### ISSUE THREAD

**Issue by davidjb** [ORCID/ORCID-Source#4117]
I’ve noticed an issue with the ORCID registry in that on the OAuth form, if I don’t have a surname associated with my profile, the string of “null” appears.  The attached screenshot demonstrates the issue on the production site — my first name is set as David and my surname is blank, but my name shows up as “David null”.  I’ve also tested this on the sandbox ORCID registry and the same issue appears as well.  As the surname is optional, the solution would be check for an empty value and not show it rather than displaying the stringified 'null'.

![screen shot 2017-10-26 at 9 04 04 am](https://user-images.githubusercontent.com/1002811/32028527-708cc242-ba32-11e7-964a-aa7a36a9eef4.png)

**Comment by alainna** [comment]
Hello David, 

Thanks for the report. Good raise, it's a known bug -- see our bug card on Trello: 
https://trello.com/c/vBlu3dfc/285

**Comment by davidjb** [comment]
Cool, great that you know about the issue. 

Since there's heaps of bugs in that Trello board (like this one) that don't appear to be on GitHub,
what's the the canonical way of reporting something or tracking progress/knowing something is being addressed?  I'd suggest adding info on reporting bugs to the README/Contributing documentation (https://github.com/ORCID/ORCID-Source/blob/master/CONTRIBUTING.md).  The latter doc only covers PRs and features but not really reporting issues.

If Trello's the official way to check bugs then definitely linking that Trello board into the same documentation would help people find what's been reported.

**Comment by rcpeters** [comment]
Fixed in current qa release (should be live this or week or next)
https://github.com/ORCID/ORCID-Source/pull/4130

**Comment by davidjb** [comment]
Thanks @rcpeters, great to know.  

@rcpeters / @alainna, any thoughts on my comment above on how/where to file future bug reports and documenting this for contributors?
