### ISSUE TITLE
Localization/Filipino translation

### ISSUE THREAD

**Issue by jcpuzs1** [ORCID/ORCID-Source#4357]
I would like to contribute in your company by means of localizing and translate it to Filipino.

**Comment by alainna** [comment]
@jcpuzs1 Thanks for your interest!

Localization of the ORCID interface is managed in the Transifex platform. [You can read more about this on the ORCID blog](https://orcid.org/blog/2017/10/26/localize-orcid).

If you would like to participate, please [create an account on Transifex](https://docs.transifex.com/getting-started/translators) and [send a request to join the ORCID translation team](https://www.transifex.com/orcid-inc-1/public/). [You can also contact us directly for information and assistance](https://orcid.org/help/contact-us).
