### ISSUE TITLE
Introduce preferredURI for profile

### ISSUE THREAD

**Issue by csarven** [ORCID/ORCID-Source#4398]
Currently under "edit websites", the user input text "webid" maps to `http://www.w3.org/2002/07/owl#sameAs`. While that's not particularly wrong, the object in question could be away from user's control. That is, people have profiles around the Web, and not all of them are created or under their direct control.

In order to take *intended* WebID profiles into account, ie. profiles that are more likely to be under a person's control that an ORCID profile can refer to, `http://www.w3.org/2000/10/swap/pim/contact#preferredURI` may be more suitable than the generic `http://www.w3.org/2002/07/owl#sameAs`.

I think `owl:sameAs` is still very useful to keep around.

Proposal for the input text from the UI and the generated mapping:

* "sameas" maps to `owl:sameAs`
* "webid" maps to `contact:preferredURI`

The only issue with this is that existing ORCID profiles that currently use the term "webid" needs to be updated and replaced with "sameas", in order to keep the existing desired mapping to `owl:sameAs` that people wanted in the first place. Can this be a batched process? Any statistics on how many people use "webid" - I'm guessing not a whole lot.

The `contact:preferredURI` value is expected to be a string (whereas `owl:sameAs` is a URI). A PR for this issue should take that subtle difference into account.

**Comment by jimmccusker** [comment]
For what it's worth, here's the argument against using the https: URI prefix. 

https://www.w3.org/DesignIssues/Security-NotTheS.html

**Comment by TomDemeranville** [comment]
Hi, I'm closing this issue as it's very old and I'm not sure of what is being asked for, or who will use it. If evidence of community demands emerges we will happily look at this again, perhaps when we look at rel="me" profile links.

**Comment by csarven** [comment]
Do I understand you correctly that you are not sure what this issue is for but at the same time you'd like to consider an alternative approach (that doesn't fit well with the existing data design/patterns)?

Happy to elaborate on anything in particular that's unclear. Simply put, the current ORCID can be re-used as a WebID that leads to extended profiles - broader use. I've implemented this use in an application.

**Comment by TomDemeranville** [comment]
I think I understand what you're proposing, but I'm not certain of the details.  I'm not sure who this impacts, so it's hard for me to prioritise.  

We've had a LOT of people asking for the rel='me' approach as this is being used by mastodon.

**Comment by csarven** [comment]
Mastodon is a part-implementation of ActivityPub. This issue impacts/helps systems that use ActivityPub, Solid (see e.g., https://www.w3.org/groups/cg/solid , https://solidproject.org/TR/protocol ), WebID. It works with your *existing* data format. You can still support rel=me separately if you really want to customise ORCID to work against particular software / service, but there is no need to conflate that with this issue. Would you like to go through the details?
