### ISSUE TITLE
Valid brackets in a doi result in an explosion of results via API search

### ISSUE THREAD

**Issue by dshorthouse** [ORCID/ORCID-Source#4499]
Given the valid doi, 10.1016/0020-7519(75)90103-4, a search via the API using the doi-self key results in WAY too many results.

For example:

`curl -X GET --header 'Accept: application/json' 'https://pub.orcid.org/v2.1/search?q=doi-self%3A10.1016%2F0020-7519(75)90103-4'
`
results in:

`"num-found": 276212`

**Comment by rcpeters** [comment]
You must use lucene syntax 
https://lucene.apache.org/core/2_9_4/queryparsersyntax.html
https://members.orcid.org/api/tutorial/search-orcid-registry
