### ISSUE TITLE
Colons in valid doi result in 500 Internal Server Error on API searches with key doi-self

### ISSUE THREAD

**Issue by dshorthouse** [ORCID/ORCID-Source#4500]
Given a valid doi, 10.1023/A:1005982530560, the following API search results in a 500 error:

`curl -X GET --header 'Accept: application/json' 'https://pub.orcid.org/v2.1/search?q=doi-self%3A10.1023%2FA%3A1005982530560'`

**Comment by rcpeters** [comment]
Filed a card to  return a 400 error:

https://trello.com/c/ziNpIkSr/4754-incorrect-lucene-query-syntax-should-result-in-400-error
