### ISSUE TITLE
ORCID sending token_type "bearer" instead of "Bearer"

### ISSUE THREAD

**Issue by coudot** [ORCID/ORCID-Source#4735]
We are using ORCID as OpenID Connect Provider and we see that the value of token_type is not conform to RFC 6750 (https://tools.ietf.org/html/rfc6750), in which we can see the token_type value must be "Bearer" and not "bearer"

**Comment by TomDemeranville** [comment]
I wish it wasn't, but token_type in the OAuth response is **not** case sensitive according to RFC6749, although the example in RFC6750 make it seems like it is https://tools.ietf.org/html/rfc6749#section-5.1 

> token_type
>          REQUIRED.  The type of the token issued as described in
>          Section 7.1.  Value is case insensitive.

This is not great as it leads to confusion and interoperability problems.  I know we're not alone in our representation (I believe github and amazon do the same in some of their APIs).  Also see this example for 'bearer' not 'Bearer' in the OpenID spec: http://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthResponse (there is an open issue on the example being incorrect, but I don't think it is based on RFC6749: https://bitbucket.org/openid/connect/issues/985/use-bearer-in-token_type-in-implicit-flow)

Also, there are several references in the wild to it being case-insensitive (for example Mastering OAuth2.0 https://books.google.co.uk/books?id=HjflCwAAQBAJ&lpg=PA80&ots=lqCx50cnaS&dq=token_type%20case%20sensitive&pg=PA80#v=onepage&q=token_type%20case%20sensitive&f=false )

We have hundreds of existing integrations and this would be a breaking change for many of them.  Even if we had to, I don't see how we could change it.

**Comment by coudot** [comment]
Ok, I did not saw that the value could be insensitive. I will fix my implementation to accept it.
