### ISSUE TITLE
ORCID do not respect standard OpenID Connect scopes

### ISSUE THREAD

**Issue by coudot** [ORCID/ORCID-Source#4736]
When testing ORCID as OpenID Connect Provider, we saw that the only authorized scope in "openid", but looking at information in /userinfo endpoint, we are getting attributes linked to "profile" scope.

To respect OIDC protocol, ORCID should allow "openid" or "openid profile" scopes, and share attributes linked to chosen scope.

**Comment by coudot** [comment]
You can read the specificiation here: http://openid.net/specs/openid-connect-core-1_0.html#ScopeClaims
 
Claims are associated to specific scopes (profile, email, address, phone) that allow users to know what information they are sharing.

In ORCID implementation, the user agrees to share only its ORCID ID (as the requested socpe in openid) but is indeed sharing other profile information.

**Comment by TomDemeranville** [comment]
The spec does not state that the Authorisation server MUST or even that it SHOULD honour the claims requested.  Nor does it state that the relying party should validate responses to see if they contain the claims requested.  It is a little vague in this area, but it does state in 5.3.2 "For privacy reasons, OpenID Providers MAY elect to not return values for some requested Claims." and in 5.4 "Claims requested by the following scopes are treated by Authorization Servers as Voluntary Claims", meaning they may or may not be made available to RPs.   There is nothing in the spec stating an Authorization Server MUST NOT or SHOULD NOT return claims that were not requested.

In section 5.5 it goes on to state "Should an OP not support this [claims] parameter and an RP uses it, the OP SHOULD return a set of Claims to the RP that it believes would be useful to the RP and the End-User using whatever heuristics it believes are appropriate" implying that extra claims may be made by the Authorization server at it's own discretion, regardless of the scope requested or claims requested.

ORCID already has a well defined privacy model and API for requesting information associated with ORCID IDs.  OpenID user info endpoints are a convenient way of obtaining PUBLIC information about the subject and are mainly in place to enable interoperability with OpenID libraries that rely on the information being in a specific location and format.  

The information within an ORCID userinfo response is only included if the ORCID Record Owner has declared that is should be made available to anyone.  Hence this is public information and does not need additional scopes to access.

For these reasons, and by the virtue of passing the OpenID conformance tests I believe we're in compliance with the specification.  

Again I'd like to ask if this is causing you any particular trouble when integrating?

**Comment by coudot** [comment]
Thanks for your answer. This is not causing any trouble in our implementation.

I understand your point of view, but I don't see why your implementation does not allow to send the "profile" scope (it leads to an error) as you are sharing claims linked to this scope. We are forced to send "scope=openid" and not anything else. I would have found better to send "scope= openid profile".

**Comment by TomDemeranville** [comment]
That's an interesting point.  

Perhaps throwing an error when extra scopes such as profile are requested is not helpful and should be changed.  We could relax our validation and allow the scopes to be requested, even though we do not use them internally.  This would be a non-breaking change for existing implementations, so could be done fairly easily.

What are your thoughts on this?

**Comment by coudot** [comment]
My opinion is that scopes are made to advertise users on what information they are sharing, so allowing the "profile" scope should also display that information on consent screen.

Do you think it would also be possible to share user email?

**Comment by TomDemeranville** [comment]
We will not be sharing email addresses via userinfo.  Less than 5% of our users choose to make this available (via our privacy focused UI) so allowing it would set up false expectations of it being there.
