### ISSUE TITLE
Webpack does not build angular_orcid_generated.js for production

### ISSUE THREAD

**Issue by jasonbarry** [ORCID/ORCID-Source#4739]
https://orcid.org/static/release-1.232.2/javascript/ng1Orcid/angular_orcid_generated.js

Notice all the `eval` statements and escaped quotes. The file weighs about 8MB.

In the [webpack config](https://github.com/ORCID/ORCID-Source/blob/78464a94dc5e2d25177d3a9b922c4094d069a20d/orcid-web/src/main/webapp/static/javascript/ng1Orcid/webpack.config.js#L6) it appears that the mode is always set to `development`. I believe calling your build script via CLI like `webpack --mode=production` will properly minify this file.

See also https://webpack.js.org/guides/production/

**Comment by lizkrznarich** [comment]
Thanks @jasonbarry, you're right that [web.config.js](https://github.com/ORCID/ORCID-Source/blob/78464a94dc5e2d25177d3a9b922c4094d069a20d/orcid-web/src/main/webapp/static/javascript/ng1Orcid/webpack.config.js) builds in dev mode, however, we have several different config files that we use for different environments. 

The config used in sandbox/prod builds in prod mode and the generated file comes in at ~1.4MB. 

The environment can be switched by passing an arg into the Maven command described in [orcid-nodejs](https://github.com/ORCID/ORCID-Source/tree/master/orcid-nodejs).

**Comment by jasonbarry** [comment]
@lizkrznarich perhaps the env var isn't making its way to production then — I'm seeing the file is 7.96MB on orcid.org. 

<img width="872" alt="screen shot 2018-07-09 at 10 39 46 am" src="https://user-images.githubusercontent.com/236451/42466711-881851e6-8364-11e8-978f-7faa2d94ab55.png">

**Comment by rcpeters** [comment]
`curl -s https://orcid.org/static/release-1.232.2/javascript/ng1Orcid/angular_orcid_generated.js | grep eval | wc -l`
produces 875 lines.

**Comment by jpeerz** [comment]
#4747

**Comment by TomDemeranville** [comment]
Closing this as very old
