### ISSUE TITLE
Adding IDN website does not work

### ISSUE THREAD

**Issue by habi** [ORCID/ORCID-Source#4993]
I wanted to add the IDN URL to my private website [1], but ORCID complains that the URL is invalid (as seen in the screenshot).
The URL is perfectly valid, so the check should not complain and make me add the workaround URL [2].

[1]: http://davidhaberthür.ch/
[2]: http://davidhaberthuer.ch/

![screenshot from 2018-10-05 11-18-27](https://user-images.githubusercontent.com/1651235/46527082-68915180-c890-11e8-9e4a-2e82dba521ea.png)

**Comment by wjrsimpson** [comment]
Hi David,

IDNs use Punycode to convert to and from plain ASCII, and web browsers know how to display them.

The underlying domain name is as follows.

http://xn--davidhaberthr-7ob.ch/

I converted to Punycode using https://www.punycoder.com.

So you can enter the Punycode version in your ORCID record and it will work.

It might be nice for ORCID to convert to Punycode automatically but, for now, this is how you will have to enter IDNs.

**Comment by habi** [comment]
Thanks for the pointer, I've added the Punycode URL.
This is also the reason why I have registered an alternate URL for my website :)

**Comment by wjrsimpson** [comment]
Great!
