### ISSUE TITLE
Inbox messages do not specify what is updated

### ISSUE THREAD

**Issue by peterdesmet** [ORCID/ORCID-Source#5007]
Inbox messages are often of the form:

![screen shot 2018-10-19 at 12 11 05](https://user-images.githubusercontent.com/600993/47212366-402d4b00-d398-11e8-9908-344b3aed2163.png)

Without indication what work was updated. Clicking `View on your record` just goes to https://orcid.org/my-orcid, rather than that work on that page. That makes the notifications of limited use: I know something has changed, but I have to figure out myself what exactly (in a list of works that can be really long).

Ideally, the title and URL/DOI of the work is mentioned in the notification. And ` View on your record` jumps to that work in your work section, so I can decide if I want to accept this source or update the visibility.

**Comment by wjrsimpson** [comment]
Hi Peter,

Thanks for your thoughts. You can vote on the idea in the ORCID Community Ideas Forum.

https://support.orcid.org/hc/en-us/community/posts/360016056814-Make-ORCID-update-notifications-more-transparent

The design of the 1.2 API made it very hard for us know what was changed. We are very close to the sunset of that version of the API, with just a couple of members still to migrate.

The version 2.0 APIs and later will allow us to know what was changed, so then we will be able to revisit this issue.

Will

**Comment by lizkrznarich** [comment]
Hi @peterdesmet , I wanted to give you an update on this  - we now have 2 projects on our roadmap 
aimed at making notifications more useful: 

https://trello.com/c/E97SY96Y/134-include-activity-title-in-work-notifications-distinguish-between-add-update-5 
https://trello.com/c/YYxfRjCw/135-include-activity-title-in-non-work-notifications-3

These will be moving onto our [Current Development board](https://trello.com/b/iuJwm8A6/orcid-current-development) in the next couple of weeks and you can follow their progress through our development cycle there.

**Comment by peterdesmet** [comment]
Awesome, thanks for the update! Looking forward to see it pop-up in my ORCID emails.

**Comment by TomDemeranville** [comment]
Notifications have been significantly improved since this issue was raised.  Closing.
