### ISSUE TITLE
Cannot Save BibTex Import (PhD Thesis)

### ISSUE THREAD

**Issue by SR--** [ORCID/ORCID-Source#5202]
When trying to import the following BibTeX, it is read in, marked as 'dissertation' (and not as dissertation-thesis, as in manual entry), but cannot be saved. No effect and no error message. What is wrong?

`@phdthesis{Smith:2008:ID2943,
author="Smith, John",
title="A Test",
school="The University of Smith",
address="Bha, GB",
year=2008,
doi="10/cbwc",
}`

If the type is changed to `@mastersthesis` the import works OK.

**Comment by caoyler** [comment]
Hi,

This is a known bug that we have merged a fix for and it will be corrected with our next release. https://github.com/ORCID/ORCID-Source/pull/5168

Thanks for letting us know about the issue,
-Catalina
