### ISSUE TITLE
Cannot close navigation bar on iOS

### ISSUE THREAD

**Issue by revi** [ORCID/ORCID-Source#5446]
|My profile|Someone else's profile (navbar unselected)|Someone else's profile (navbar selected)|
|---|---|---|
|![56996C57-78A8-4466-A674-9DDD9713CD98](https://user-images.githubusercontent.com/7630875/58168880-4e469f80-7cca-11e9-90f8-7684dcc566be.png)|![E81409C6-6472-43D8-AB65-E7EB7ACD0860](https://user-images.githubusercontent.com/7630875/58168900-59013480-7cca-11e9-8e37-5cf922885245.png)|![C7272071-27E1-4F68-B809-A7C7E123C4AD](https://user-images.githubusercontent.com/7630875/58168922-64ecf680-7cca-11e9-8566-af1e85ba883d.png)|

I can open/close the navbar on my profile as I wish, but for someone else's profile, I have no freedom: it is displayed whether I want to see it or not.

**Comment by lizkrznarich** [comment]
Hi @revi , thanks for pointing this out. It also came up in our QA testing, and we have a fix that's live in https://sandbox.orcid.org and will be deployed to production in our next release (which should happen in the next few days). You can follow the progress of this fix on https://trello.com/c/EP2y0NlR/5914-unable-to-toggle-the-mobile-menu-off-on-the-public-page-this-is-also-on-prod

**Comment by lizkrznarich** [comment]
@revi This fix was deployed to production today
