### ISSUE TITLE
Fix JSON-LD representation

### ISSUE THREAD

**Issue by csarven** [ORCID/ORCID-Source#5452]
`curl -LH'Accept: application/ld+json' https://orcid.org/0000-0002-0880-9125` is not returning all information and correctly.

Compare with `curl -LH'Accept: text/turtle' https://orcid.org/0000-0002-0880-9125`

**Comment by TomDemeranville** [comment]
This is expected behaviour.  JSON LD returns schema.org metadata.  Other LOD content types use FOAF etc.

See https://github.com/ORCID/ORCID-Source/blob/master/CONTENT_NEGOTIATION.md

**Comment by csarven** [comment]
It is not just a matter of different vocabulary use but the data between the representations differ. There is also inconsistent granularity among them - not functionally equivalent either. I think this is a bug and suggest revisiting conneg.

**Comment by stain** [comment]
I think it would make sense for schema.org properties to also be returned in the other LOD types - they are just different serializations of the same model. It would perhaps be less important for the (older) FOAF properties to appear in the JSON-LD output.

A more pressing issue is inconsistent identifiers:

```json
  "@type" : "Person",
  "@id" : "http://orcid.org/0000-0002-0880-9125",
  "mainEntityOfPage" : "http://orcid.org/0000-0002-0880-9125",
```

The second line here having the same identifier is wrong - https://schema.org/mainEntityOfPage says _"Indicates a page (or other CreativeWork) for which this thing is the main entity being described"_ - but a person is presumably not something we should think of as a `CreativeWork` or a web page!!



This JSON-LD  uses the `http` version of ORCID  - however https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier says to use `https`:

> **Expressing the ORCID iD**

> The ORCID iD is expressed as an https URI, i.e. the 16-digit identifier is preceded by "https://orcid.org/". A hyphen is inserted every 4 digits of the identifier to aid readability. 

> **Storage of the ORCID iD in a database**

> When stored, the ORCID iD should be expressed as a full https URI: https://orcid.org/xxxx-xxxx-xxxx-xxxx, complete with the protocol (https://), and with hyphens in the identifier (xxxx-xxxx-xxxx-xxxx). 

The Turtle version was previously changed to use `https` variant of ORCID for this same reason.

**Comment by TomDemeranville** [comment]
> The second line here having the same identifier is wrong - https://schema.org/mainEntityOfPage says "Indicates a page (or other CreativeWork) for which this thing is the main entity being described" - but a person is presumably not something we should think of as a CreativeWork or a web page!!

So I read this differently -> That the page (http://orcid.org/0000-0002-0880-9125) is about the entity being described in the JSON document.

> This JSON-LD uses the http version of ORCID - however https://support.orcid.org/hc/en-us/articles/360006897674-Structure-of-the-ORCID-Identifier says to use https:

This is not good.  I have raised a bug to get this fixed.  Thanks for pointing it out.
