### ISSUE TITLE
  Please check your client id, scopes and redirect URIs.

### ISSUE THREAD

**Issue by brayanrodbajo** [ORCID/ORCID-Source#5457]
I am trying to authenticate a JupyterHub service with ORCiD. I am working on a test server (without HTTPS nor DNS). They request for the endpoint with user data and after looking for it too much time, I found this one: https://sandbox.orcid.org/oauth/userinfo. But I got the following error when redirecting to https://orcid.org/signin?oauth&response_type=code&state=(...)&client_id=(...)&redirect_uri=http%3A%2F%2F50.116.16.56%3A8000%2Fhub%2Foauth_callback: 
```
Please check your client id, scopes and redirect URIs.
```

However, when I am authenticated in the session, I got: 
```
There has been a problem with the server. If this problem persists, please contact support.
```

Thank you in advance.

**Comment by lizkrznarich** [comment]
Hi @brayanrodbajo those 2 error messages can occur for a wide variety of reasons. For help troubleshooting, see https://members.orcid.org/api/resources/troubleshooting . For further help using our APIs, please contact our support team https://support.orcid.org/hc/en-us/requests/new or our ORCID API Users group, as our support team does not monitor Github issues.
