### ISSUE TITLE
Countries do not display on personal page

### ISSUE THREAD

**Issue by devurandom** [ORCID/ORCID-Source#5517]
https://orcid.org/my-orcid displays e.g. `University Computing Centre Heidelberg: Heidelberg, DE`, but https://orcid.org/0000-0001-6250-267X displays `University Computing Centre Heidelberg: Heidelberg`. The latter page is missing the country.

**Comment by lizkrznarich** [comment]
Hi @devurandom , thanks for raising this and sorry about the issue! I've submitted a fix on https://github.com/ORCID/ORCID-Source/pull/5518 and we'll include it our next our next production release, which should be sometime this week.
