### ISSUE TITLE
Add filtering to GET /works api

### ISSUE THREAD

**Issue by uqclien** [ORCID/ORCID-Source#5686]
Is it possible to add a filtering feature to the GET /works API, e.g. filter by external id and source

**Comment by amontenegro** [comment]
Hi @uqclien, 

Thanks for getting in touch with us, we are welcome to new ideas and suggestions, please read the following guidelines:  

https://support.orcid.org/hc/en-us/articles/360006897594-How-are-new-features-decided-

And submit your idea to our community forum:

https://support.orcid.org/hc/en-us/community/topics

Thanks

**Comment by TomDemeranville** [comment]
Hi @uqclien I've added your request to our member feedback trello board.  I think it's a very reasonable ask and something we should strongly consider putting in place.  You can track the progress here: https://trello.com/c/NQjTJYr9/28-add-a-filtering-to-get-works-to-allow-filtering-by-external-id-and-source

**Comment by TomDemeranville** [comment]
Closing as the feedback has been captured.  This is under consideration for the next API version.
