### ISSUE TITLE
Is 'disambiguated-organization' column must required when updating teachers' employment in api 3.0? 

### ISSUE THREAD

**Issue by maotingyang** [ORCID/ORCID-Source#5853]
We used to use api 2.0, and the 'disambiguated-organization' column is not required. Now we try to upgrade to v3.0, and found that this column seems become required? If so, is there a way to update teachers' employment without fill in this column? Since our database doesn't have these data......

**Comment by caoyler** [comment]
Hi,

Disambiguated-organization is required now with 3.0. If you message our team at support@orcid.org we will work with you to find a solution- perhaps we can help you get the disambiguated organization information to add to your database so you can post it to ORCID.

Best,
-Catalina
