### ISSUE TITLE
Release V.3 JAXB object model on maven central

### ISSUE THREAD

**Issue by lap82** [ORCID/ORCID-Source#5860]
I'm wonder if it is possible share on Maven Central https://mvnrepository.com/repos/central the artifact related the ORCID JAXB Model at https://github.com/ORCID/ORCID-Source/tree/master/orcid-model/src/main/java/org/orcid/jaxb/model/v3/release

At DSpace-CRIS project (and DSpace project please check https://github.com/DSpace/orcid-jaxb-api/pull/1) we using the ORCID XSDs to build the jaxb orcid model from scratch.
Build the same model that you released at https://github.com/ORCID/ORCID-Source/tree/master/orcid-model/src/main/java/org/orcid/jaxb/model/v3/release is difficult and we spend many time to understand tha changes when we work to upgrade integration.

If you released the artifact on Maven Central we can keep the official object model and we not need to release it externally and tune it on the JAXB binding to reach the same result (like the "FuzzyDate" model or the "Affiliation" hierarchy model).

This is an idea. Thank you very much for your work.

**Comment by abollini** [comment]
any update on that? there is any plan from ORCID to release an official jaxb binding artifact on maven central?

**Comment by lap82** [comment]
Please, any news?

**Comment by lizkrznarich** [comment]
Hi there, orcid-model was published to Maven in April 2020 per https://groups.google.com/g/orcid-api-users/c/BbiZNp8SM0I/m/3yNhlvpmAQAJ . It's located at https://mvnrepository.com/artifact/org.orcid/orcid-model and the source code has been moved to a separate repo, https://github.com/ORCID/orcid-model . Hope this helps!
