### ISSUE TITLE
ORCID API returning HTML instead of JSON 

### ISSUE THREAD

**Issue by anaritagomes** [ORCID/ORCID-Source#6145]
Hi all, I am not sure if this is an issue or just a misunderstanding from my side, but I when I call your API to build the authorization URL I am getting HTML instead of JSON (both with code and via Postman). I am currently using Django with Python 3:

       `import requests

        url = "https://orcid.org/oauth/authorize"
        payload = {
            "client_id": client_id,
            "response_type": 'code',
            "grant_type": "client_credentials",
            "scope": "/authenticate",
            "redirect_uri": redirect_uri,
        }

        response = requests.post(url=url, params=payload)
        print(response.text)`

        
Although the curl request works perfectly!
I tried both with my sandbox client credentials and in production. Any help would be truly appreciated, thank you.

**Comment by DanielPalafox** [comment]
Hi Rita, If you want to modify a record using the API, you must first obtain the authorization of the user, so the first step would be to create an URL with your parameters and then the user must open it in a browser and authorize it. 

You can check our documentation using [postman](https://postman.orcid.org/) for more references.
