### ISSUE TITLE
/me endpoint

### ISSUE THREAD

**Issue by asencis** [ORCID/ORCID-Source#6150]
Just making a quick request if at all possible.

Could we have a /me API endpoint that takes in a user's token as Bearer auth and returns that user's object details...

**Comment by TomDemeranville** [comment]
Hi,

We have a userinfo endpoint at https://orcid.org/oauth/userinfo that works as you expect.  

Documentation can found at https://github.com/ORCID/ORCID-Source/blob/master/orcid-web/ORCID_AUTH_WITH_OPENID_CONNECT.md#other-endpoints

Hope that helps!

**Comment by asencis** [comment]
@TomDemeranville Ah, perfect. Thanks Tom!

**Comment by asencis** [comment]
@TomDemeranville Sorry Tom, I'm just reopening this issue. Is there any possibility that this endpoint could return an email address?

**Comment by TomDemeranville** [comment]
97.7% of our users keep their email address private, so we didn't include it in the userinfo as it would be disappointingly empty in most cases.

**Comment by asencis** [comment]
@TomDemeranville Could I suggest the following changes:

- Endpoint is duplicated, for backwards compatibility, to also be accessible on `'https://orcid.org/me'`
- Endpoint returns the email / person if allowed, if not - empty email key => value (e.g., `email: null`).

**Comment by TomDemeranville** [comment]
Hi, thanks for the suggestions.  We will look at them in 2023 when we're also looking at PKCE.
