### ISSUE TITLE
Enable autocomplete URLs with resolution prefixes for WOSUID and EID

### ISSUE THREAD

**Issue by iago-pssjd** [ORCID/ORCID-Source#6200]
When adding DOI, PMID or PMC identifier types of a work, the URL is automatically added, but it is not when adding `WOSUID` or `EID`,. However, it could be, since there are well defined URLs for such id's.

Indeed, for example, the next URL works for `WOS:000568567200012`, or for any other `WOSUID`.
```
https://gateway.webofknowledge.com/gateway/Gateway.cgi?GWVersion=2&SrcApp=Publons&SrcAuth=Publons_CEL&KeyUT=WOS:000568567200012&DestLinkType=FullRecord&DestApp=WOS_CPL
```
or also
```
https://gateway.webofknowledge.com/gateway/Gateway.cgi?GWVersion=2&SrcApp=Publons&SrcAuth=Publons_CEL&DestLinkType=FullRecord&DestApp=WOS_CPL&KeyUT=WOS:000568567200012
```

For `EID` there are various options. Let's say the `EID` is `2-s2.0-85087004662`. Then both next URL's link to the same web:
```
http://www.scopus.com/record/display.url?eid=2-s2.0-85087004662&origin=resultslist
https://www.scopus.com/inward/record.uri?partnerID=HzOxMe3b&scp=85087004662&origin=inward
https://www.scopus.com/inward/record.uri?partnerID=HzOxMe3b&scp=85087004662
```
The first one (which I have found in # https://kitchingroup.cheme.cmu.edu/blog/2015/06/07/Getting-a-Scopus-EID-from-a-DOI/
) sometimes does not open at first attempt. I got none problem with the second one.

Another option would be link to the cites of the paper. These would be (the first one also found in the linked blog above):
```
http://www.scopus.com/results/citedbyresults.url?sort=plf-f&cite=2-s2.0-85087004662&src=s&imp=t&sot=cite&sdt=a&sl=0&origin=recordpage
https://www.scopus.com/inward/citedby.uri?partnerID=HzOxMe3b&scp=85087004662&origin=inward
https://www.scopus.com/inward/citedby.uri?partnerID=HzOxMe3b&scp=85087004662
```

I do not know if this is the suitable place to ask for this. Let me know if there is a better place to suggest this.

Thank you!

**Comment by TomDemeranville** [comment]
Hi there, we'd love to be able to do this, but need a free to use and machine readable API, not just webpages.  If you know of such things, please let us know, but I haven't been able to find them.

Closing
