### ISSUE TITLE
Update cryptographic primitives

### ISSUE THREAD

**Issue by guilloux-valentin** [ORCID/ORCID-Source#6266]
Hello,

A fast manual source code audit may suggest that `package org.orcid.core.crypto;` use (or has used in the past) vulnerable cryptographic primitive for Password Based Encryption (DES and MD5) that are not considered secure anymore. 

Please consider updating to newer encryption scheme as described in https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#password-hashing-algorithms or remove the coresponding code if not used anymore in the production application authentication workflow.

**Comment by amontenegro** [comment]
Hi @guilloux-valentin!

I'm Angel, tech lead of the ORCID registry.

Thanks for raising this, this is legacy code that we haven't properly removed from our repo; I'm creating a card for it.

Thanks
