### ISSUE TITLE
Expanded-Search: Added more information for affiliation 

### ISSUE THREAD

**Issue by lap82** [ORCID/ORCID-Source#6330]
The expanded-search endpoint https://info.orcid.org/documentation/api-tutorials/api-tutorial-searching-the-orcid-registry/#Expanded_Search don't discriminate the type of affiliations. 
Employment, Education, Memberships, Invited Positions all are managed in same manner and ordered in alphabetically order, but if possible the response of expanded-search should be show this information and in my opinion the response also have to tag the affiliation with current/past information:
e.g. 
`    <expanded-search:expanded-result>
        <expanded-search:orcid-id>0000-0002-2436-0000</expanded-search:orcid-id>
        <expanded-search:given-names>Dave Theodore</expanded-search:given-names>
        <expanded-search:family-names>Spaceman</expanded-search:family-names>
        <expanded-search:other-name>D Spaceman</expanded-search:other-name>
        <expanded-search:other-name>D T Spaceman</expanded-search:other-name>
        <expanded-search:institution-name affiliationtype="employment" affiliationstatus="current">The University of The Mars</expanded-search:institution-name>
        <expanded-search:institution-name affiliationtype="employment" affiliationstatus="past">The University of The Moon</expanded-search:institution-name>
        <expanded-search:institution-name affiliationtype="invitedposition" affiliationstatus="current">Saturn Institute</expanded-search:institution-name>
    </expanded-search:expanded-result>`

**Comment by TomDemeranville** [comment]
Hi, we're hoping to improve this in 2023 when we take a fresh look at how we deal with professional activities (as opposed to employment affiliations and education items).
