### ISSUE TITLE
Token Exchange returns cloudflare page

### ISSUE THREAD

**Issue by redagito** [ORCID/ORCID-Source#6607]
I built a sample oauth2 login with orcid at bluetree.rf.gd.
The oauth2 flow used to work for some time but now the token exchange step fails, as instead of a json, I am receiving a cloudflare response page with user captcha validation.
This does not make any sense to me as the one doing this request should be the server.

I tested this code on another server / URL and it works. Did my domain get blacklisted somehow?
Relevant code (PHP)
```
$curl = curl_init();
curl_setopt($curl, CURLOPT_URL, "https://orcid.org/oauth/token");
curl_setopt($curl, CURLOPT_POST, true);
curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);

$headers = array(
    "Accept: application/json",
    "Content-Type: application/x-www-form-urlencoded"
);
curl_setopt($curl, CURLOPT_HTTPHEADER, $headers);

$data = array(
    "client_id" => ORCID_CLIENT_ID,
    "client_secret" => ORCID_CLIENT_SECRET,
    "grant_type" => "authorization_code",
    "redirect_uri" => ORCID_REDIRECT_URL,
    "code" => $authCode
);
curl_setopt($curl, CURLOPT_POSTFIELDS, http_build_query($data));

$response = curl_exec($curl);
curl_close($curl);
// $response contains the cloudflare html
$arr = json_decode($response, true);
// $arr is null
```

**Comment by wjrsimpson** [comment]
Hi!

If you are from an [ORCID member organization](https://orcid.org/members), you'll be able to get support by email from ORCID. If not, you can get help from our community on the [ORCID API users group](https://groups.google.com/g/orcid-api-users).

Please can you send your query to one of those channels. (Sorry, I know it's confusing that you can raise issues here, but it's best if I send you to the right channel.)

Best wishes,

Will
