### ISSUE TITLE
Website URLs are broken by lowercasing

### ISSUE THREAD

**Issue by vlysikov** [ORCID/ORCID-Source#6862]
URLs in added websites are converted to lowercase, which breaks case-sensitive links.
In particular, Google Scholar links contain case-sensitive user identifiers. In general, only the schema and hostname in URLs are defined to be case-insensitive in the RFC, so lowercasing whole URLs is expected to introduce broken links.

**Comment by amontenegro** [comment]
This is now fixed. Thanks for raising the bug @vlysikov. https://trello.com/c/4w3HGRGC/443-qa-items-in-the-websites-section-are-converted-to-lowercase-when-editing
