### ISSUE TITLE
Add `rel=me` microformat support

### ISSUE THREAD

**Issue by capjamesg** [ORCID/ORCID-Source#7015]
Hello there! I have just set up my profile on ORCiD and noticed the field to add arbitrary professional links (i.e. to one's portfolio).

It would be great if this field supported `rel=me`, a web standard used to indicate that the destination of a link is owned by the same person who owns a profile.

[View the rel=me documentation](https://microformats.org/wiki/rel-me)

If I ORCiD supported `rel=me`, [my profile](https://orcid.org/0009-0006-3736-1653) could say:

```
<a href="https://jamesg.blog" rel="me">Personal Website</a>
```

And I could then add a link to my ORCiD ID (which I have already done!) on my website:

```
<link rel="me" href="https://orcid.org/0009-0006-3736-1653" />
```

This bi-directional link could serve as attestation that I own both jamesg.blog and the associated ORCiD page.

Many sites support publishing rel=me, including GitHub and Mastodon. Many sites also support consuming rel=me, which involves verifying a bi-directional link exists and showing that is the case (i.e. by a green checkmark). Mastodon supports this, for example (see the purple checkmark on https://indieweb.social/@capjamesg next to my domain name).

**Comment by Hugo-Heagren** [comment]
Just so you're aware, this has been discussed before:
- there are ongoing updates in [this github issue](https://github.com/ORCID/ORCID-Source/issues/6668)
- which links to [this trello card](https://trello.com/c/M0pKNCPk) on ORCID's (internal?) board

**Comment by capjamesg** [comment]
Ah, thank you so much @Hugo-Heagren! I will close this issue since there is already an active one.
